In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.data.load_data import load_processed_datasets

In [3]:
datasets = load_processed_datasets()

Loaded 5 processed datasets successfully.

In [4]:
MASTER_PATH = PROJECT_ROOT / "data" / "processed" / "master_dataset.csv"

print(MASTER_PATH)
print(MASTER_PATH.exists())

d:\pricing-optimization-system\data\processed\master_dataset.csv
True

In [5]:
master_df = pd.read_csv(MASTER_PATH)

In [6]:
master_df.shape

(112650, 29)

In [7]:
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,total_payment_value,payment_count,max_installments
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,38.71,3.0,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,141.46,1.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,179.12,1.0,3.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,59.0,468.0,3.0,450.0,30.0,10.0,20.0,72.20,1.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,38.0,316.0,4.0,250.0,51.0,15.0,15.0,28.62,1.0,1.0

In [8]:
print("Rows:", len(master_df))
print("Columns:", len(master_df.columns))

Rows: 112650
Columns: 29

In [9]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   customer_id                    112650 non-null  object
 2   order_status                   112650 non-null  object
 3   order_purchase_timestamp       112650 non-null  object
 4   order_approved_at              112635 non-null  object
 5   order_delivered_carrier_date   111456 non-null  object
 6   order_delivered_customer_date  110196 non-null  object
 7   order_estimated_delivery_date  112650 non-null  object
 8   customer_unique_id             112650 non-null  object
 9   customer_zip_code_prefix       112650 non-null  int64
 10  customer_city                  112650 non-null  object
 11  customer_state                 112650 non-null  object
 12  order_item_id                  112650 non-null  int64
 13  product_id                     112650 non-null  object
 14  seller_id                      112650 non-null  object
 15  shipping_limit_date            112650 non-null  object
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          111047 non-null  object
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               111046 non-null  float64
 23  product_length_cm              111046 non-null  float64
 24  product_height_cm              111046 non-null  float64
 25  product_width_cm               111046 non-null  float64
 26  total_payment_value            112647 non-null  float64
 27  payment_count                  112647 non-null  float64
 28  max_installments               112647 non-null  float64
dtypes: float64(12), int64(2), object(15)
memory usage: 24.9+ MB

In [10]:
print(
    master_df["order_purchase_timestamp"].dtype
)

object

In [11]:
# ============================================================
# 1. DATETIME CONVERSION
# ============================================================

datetime_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date"
]

for col in datetime_columns:
    if col in master_df.columns:
        master_df[col] = pd.to_datetime(
            master_df[col],
            errors="coerce"
        )

print("Datetime conversion completed.")

Datetime conversion completed.

In [12]:
print(master_df["order_purchase_timestamp"].dtype)

datetime64[ns]

In [13]:
# ============================================================
# 2. BASIC DATE FEATURES
# ============================================================

master_df["order_year"] = (
    master_df["order_purchase_timestamp"].dt.year
)

master_df["order_month"] = (
    master_df["order_purchase_timestamp"].dt.month
)

master_df["order_day"] = (
    master_df["order_purchase_timestamp"].dt.day
)

master_df["order_day_of_week"] = (
    master_df["order_purchase_timestamp"].dt.dayofweek
)

print(
    master_df[
        [
            "order_year",
            "order_month",
            "order_day",
            "order_day_of_week"
        ]
    ].head()
)

   order_year  order_month  order_day  order_day_of_week
0        2017           10          2                  0
1        2018            7         24                  1
2        2018            8          8                  2
3        2017           11         18                  5
4        2018            2         13                  1

In [14]:
master_df["order_day"] = master_df["order_purchase_timestamp"].dt.day

master_df["order_day_of_week"] = (
    master_df["order_purchase_timestamp"].dt.dayofweek
)

master_df["order_hour"] = (
    master_df["order_purchase_timestamp"].dt.hour
)

master_df["order_week"] = (
    master_df["order_purchase_timestamp"].dt.isocalendar().week.astype(int)
)

master_df["is_weekend"] = (
    master_df["order_day_of_week"] >= 5
).astype(int)

print(
    master_df[
        [
            "order_purchase_timestamp",
            "order_year",
            "order_month",
            "order_day",
            "order_day_of_week",
            "order_hour",
            "order_week",
            "is_weekend"
        ]
    ].head()
)

  order_purchase_timestamp  order_year  order_month  order_day  \
0      2017-10-02 10:56:33        2017           10          2
1      2018-07-24 20:41:37        2018            7         24
2      2018-08-08 08:38:49        2018            8          8
3      2017-11-18 19:28:06        2017           11         18
4      2018-02-13 21:18:39        2018            2         13

   order_day_of_week  order_hour  order_week  is_weekend
0                  0          10          40           0
1                  1          20          30           0
2                  2           8          32           0
3                  5          19          46           1
4                  1          21           7           0

In [15]:
date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date"
]

for col in date_columns:
    if col in master_df.columns:
        master_df[col] = pd.to_datetime(
            master_df[col],
            errors="coerce"
        )

In [16]:
master_df["delivery_days"] = (
    master_df["order_delivered_customer_date"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

In [17]:
master_df["estimated_delivery_days"] = (
    master_df["order_estimated_delivery_date"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

In [18]:
master_df["delivery_delay_days"] = (
    master_df["delivery_days"]
    - master_df["estimated_delivery_days"]
)

In [19]:
master_df["is_delayed"] = (
    master_df["delivery_delay_days"] > 0
).astype(int)

In [20]:
print(
    master_df[
        [
            "delivery_days",
            "estimated_delivery_days",
            "delivery_delay_days",
            "is_delayed"
        ]
    ].describe()
)

       delivery_days  estimated_delivery_days  delivery_delay_days  \
count  110196.000000            112650.000000        110196.000000
mean       12.472631                23.835035           -11.333149
std         9.445655                 8.887306            10.162342
min         0.533414                 2.008009          -146.016123
25%         6.736262                18.370035           -16.321042
50%        10.184282                23.255880           -12.046788
75%        15.541097                28.471458            -6.476803
max       209.628611               155.135463           188.975081

          is_delayed
count  112650.000000
mean        0.077364
std         0.267169
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [21]:
master_df["item_total_value"] = (
    master_df["price"]
    + master_df["freight_value"]
)

In [22]:
master_df["freight_percentage"] = (
    master_df["freight_value"]
    / master_df["price"].replace(0, pd.NA)
) * 100

In [23]:
master_df["payment_price_difference"] = (
    master_df["total_payment_value"]
    - master_df["item_total_value"]
)

In [24]:
import numpy as np

master_df["log_price"] = np.log1p(master_df["price"])

In [25]:
print(
    master_df[
        [
            "price",
            "freight_value",
            "item_total_value",
            "freight_percentage",
            "total_payment_value",
            "payment_price_difference",
            "log_price"
        ]
    ].head()
)

    price  freight_value  item_total_value  freight_percentage  \
0   29.99           8.72             38.71           29.076359
1  118.70          22.76            141.46           19.174389
2  159.90          19.22            179.12           12.020013
3   45.00          27.20             72.20           60.444444
4   19.90           8.72             28.62           43.819095

   total_payment_value  payment_price_difference  log_price
0                38.71              0.000000e+00   3.433665
1               141.46              0.000000e+00   4.784989
2               179.12              0.000000e+00   5.080783
3                72.20              0.000000e+00   3.828641
4                28.62              3.552714e-15   3.039749

In [26]:
# ============================================================
# CUSTOMER HISTORICAL ORDER COUNT
# ============================================================

customer_data = (
    master_df[
        [
            "order_id",
            "customer_unique_id",
            "order_purchase_timestamp"
        ]
    ]
    .drop_duplicates("order_id")
    .copy()
)

customer_data = customer_data.sort_values(
    [
        "customer_unique_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

customer_data["customer_order_count"] = (
    customer_data
    .groupby("customer_unique_id")
    .cumcount()
)

master_df = master_df.drop(
    columns=["customer_order_count"],
    errors="ignore"
)

master_df = master_df.merge(
    customer_data[
        [
            "order_id",
            "customer_order_count"
        ]
    ],
    on="order_id",
    how="left"
)

master_df["is_repeat_customer"] = (
    master_df["customer_order_count"] > 0
).astype(int)

print(
    master_df[
        [
            "customer_unique_id",
            "customer_order_count",
            "is_repeat_customer"
        ]
    ].head()
)

                 customer_unique_id  customer_order_count  is_repeat_customer
0  7c396fd4830fd04220f754e42b4e5bff                     1                   1
1  af07308b275d755c9edb36a90c618231                     0                   0
2  3a653a41f6f9fc3d2a113cf8398680e8                     0                   0
3  7c142cf63193a1473d2e66489a9ae977                     0                   0
4  72632f0f9dd73dfee390c9b22eb56dd6                     0                   0

In [27]:
# ============================================================
# PRODUCT HISTORICAL ORDER COUNT
# ============================================================

product_data = (
    master_df[
        [
            "order_id",
            "product_id",
            "order_purchase_timestamp"
        ]
    ]
    .copy()
)

product_data = product_data.sort_values(
    [
        "product_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

product_data["product_order_count"] = (
    product_data
    .groupby("product_id")
    .cumcount()
)

master_df = master_df.drop(
    columns=[
        "product_order_count",
        "product_popularity"
    ],
    errors="ignore"
)

master_df = master_df.merge(
    product_data[
        [
            "order_id",
            "product_order_count"
        ]
    ],
    on="order_id",
    how="left"
)

master_df["product_popularity"] = (
    master_df["product_order_count"]
)

print(
    master_df[
        [
            "product_id",
            "product_order_count",
            "product_popularity"
        ]
    ].head()
)

                         product_id  product_order_count  product_popularity
0  87285b34884572647811a353c7ac498a                    2                   2
1  595fac2a385ac33a80bd5114aec74eb8                   87                  87
2  aa4383b373c6aca5d8797843e5594415                    2                   2
3  d0b61bfb1de832b15ba9d266ca96e5b0                    1                   1
4  65266b2da20d04dbe00c5c2d3bb7859e                    8                   8

In [28]:
# ============================================================
# SELLER HISTORICAL ORDER COUNT
# ============================================================

seller_data = (
    master_df[
        [
            "order_id",
            "seller_id",
            "order_purchase_timestamp"
        ]
    ]
    .copy()
)

seller_data = seller_data.sort_values(
    [
        "seller_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

seller_data["seller_order_count"] = (
    seller_data
    .groupby("seller_id")
    .cumcount()
)

master_df = master_df.drop(
    columns=["seller_order_count"],
    errors="ignore"
)

master_df = master_df.merge(
    seller_data[
        [
            "order_id",
            "seller_order_count"
        ]
    ],
    on="order_id",
    how="left"
)

print(
    master_df[
        [
            "seller_id",
            "seller_order_count"
        ]
    ].head()
)

                          seller_id  seller_order_count
0  3504c0cb71d7fa48d967e0e4c94d59d9                  42
1  289cdb325fb7e7f891c38608bf9e0962                 104
2  4869f7a5dfa277a7dca6462dcf3b52b2                1181
3  66922902710d126a0e7d26b0e3805106                  44
4  2c9e548be18521d1c43cde1c582c6de8                  78

In [29]:
# ============================================================
# CATEGORY HISTORICAL ORDER COUNT
# ============================================================
# Counts how many PREVIOUS orders belonged to the same category.
# The current order is NOT included.
# This avoids data leakage and prevents a many-to-many merge.
# ============================================================

# Remove old version if it already exists
master_df = master_df.drop(
    columns=["category_order_count"],
    errors="ignore"
)

# Keep only the information needed
category_data = master_df[
    [
        "order_id",
        "product_category_name",
        "order_purchase_timestamp"
    ]
].copy()

# Remove duplicate order-category combinations
# because one order may contain multiple products from the same category
category_data = category_data.drop_duplicates(
    subset=[
        "order_id",
        "product_category_name"
    ]
)

# Sort chronologically
category_data = category_data.sort_values(
    [
        "product_category_name",
        "order_purchase_timestamp",
        "order_id"
    ]
)

# Count ONLY previous orders in the same category
# cumcount() starts at 0, so the current order is not counted
category_data["category_order_count"] = (
    category_data
    .groupby("product_category_name")
    .cumcount()
)

# Keep only the columns needed to add the feature back
category_history = category_data[
    [
        "order_id",
        "product_category_name",
        "category_order_count"
    ]
]

# IMPORTANT:
# Merge using BOTH order_id AND product_category_name.
# This prevents the many-to-many merge that caused the MemoryError.
master_df = master_df.merge(
    category_history,
    on=[
        "order_id",
        "product_category_name"
    ],
    how="left",
    validate="many_to_one"
)

print("Category historical order count created successfully.")

print(
    master_df[
        [
            "order_id",
            "product_category_name",
            "category_order_count"
        ]
    ].head(10)
)

Category historical order count created successfully.
                           order_id  product_category_name  \
0  e481f51cbdc54678b7cc49136f2d6af7  utilidades_domesticas
1  53cdb2fc8bc7dce0b6741e2150273451             perfumaria
2  47770eb9100c2d0c44946d9cf07ec65d             automotivo
3  949d5b44dbf5de918fe9c16f97b45f8a               pet_shop
4  ad21c59c0840e6cb83a9ceb5573f8159              papelaria
5  a4591c265e18cb1dcee52889e2d8acc3             automotivo
6  136cce7faa42fdb2cefd53fdc79a6098                    NaN
7  6514b8ad8028c9f2cc2374ded245783f             automotivo
8  76c6e866289321a7c93b82b54852dc33       moveis_decoracao
9  e69bfb5eb88e0ed6a785585b27e16dbf      moveis_escritorio

   category_order_count
0                1673.0
1                2898.0
2                3655.0
3                 571.0
4                1357.0
5                 505.0
6                   NaN
7                 324.0
8                 137.0
9                 348.0

In [30]:
# ============================================================
# STATE AND CITY HISTORICAL ORDER COUNTS
# ============================================================

location_data = (
    master_df[
        [
            "order_id",
            "customer_state",
            "customer_city",
            "order_purchase_timestamp"
        ]
    ]
    .drop_duplicates("order_id")
    .copy()
)

location_data = location_data.sort_values(
    [
        "order_purchase_timestamp",
        "order_id"
    ]
)

location_data["state_order_count"] = (
    location_data
    .groupby("customer_state")
    .cumcount()
)

location_data["city_order_count"] = (
    location_data
    .groupby("customer_city")
    .cumcount()
)

master_df = master_df.drop(
    columns=[
        "state_order_count",
        "city_order_count"
    ],
    errors="ignore"
)

master_df = master_df.merge(
    location_data[
        [
            "order_id",
            "state_order_count",
            "city_order_count"
        ]
    ],
    on="order_id",
    how="left"
)

print(
    master_df[
        [
            "customer_state",
            "state_order_count",
            "customer_city",
            "city_order_count"
        ]
    ].head()
)

  customer_state  state_order_count            customer_city  city_order_count
0             SP              10618                sao paulo              3796
1             BA               3120                barreiras                49
2             GO               1928               vianopolis                 2
3             RN                182  sao goncalo do amarante                 6
4             SP              21827              santo andre               423

In [31]:
if "product_description_length" in master_df.columns:
    master_df["product_description_length"] = (
        master_df["product_description_length"].fillna(0)
    )

if "product_photos_qty" in master_df.columns:
    master_df["product_photos_qty"] = (
        master_df["product_photos_qty"].fillna(0)
    )

if "product_weight_g" in master_df.columns:
    master_df["product_weight_g"] = (
        master_df["product_weight_g"].fillna(
            master_df["product_weight_g"].median()
        )
    )

In [32]:
print(
    [
        col
        for col in master_df.columns
        if "payment" in col.lower()
    ]
)

['total_payment_value', 'payment_count', 'payment_price_difference']

In [33]:
master_df["total_payment_value"] = (
    master_df["total_payment_value"].fillna(0)
)

master_df["payment_count"] = (
    master_df["payment_count"].fillna(0)
)

In [34]:
master_df["payment_price_ratio"] = (
    master_df["total_payment_value"]
    / master_df["price"].replace(0, pd.NA)
)

In [35]:
missing_values = (
    master_df.isnull()
    .sum()
    .sort_values(ascending=False)
)

print(missing_values[missing_values > 0])

order_delivered_customer_date    23794
delivery_delay_days              23794
delivery_days                    23794
order_delivered_carrier_date     18428
product_width_cm                 15119
product_height_cm                15119
product_length_cm                15119
category_order_count             15118
product_description_lenght       15118
product_name_lenght              15118
product_category_name            15118
payment_price_difference            81
max_installments                    81
order_approved_at                   29
dtype: int64

In [36]:
numeric_columns = master_df.select_dtypes(
    include=["int64", "float64"]
).columns

for col in numeric_columns:
    master_df[col] = master_df[col].fillna(
        master_df[col].median()
    )

In [37]:
categorical_columns = master_df.select_dtypes(
    include=["object"]
).columns

for col in categorical_columns:
    master_df[col] = master_df[col].fillna("Unknown")

In [38]:
print(
    "Total missing values:",
    master_df.isnull().sum().sum()
)

Total missing values: 42251

In [39]:
date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date"
]

for col in date_columns:
    master_df[col] = pd.to_datetime(master_df[col], errors="coerce")

print(master_df[date_columns].dtypes)

order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
shipping_limit_date              datetime64[ns]
dtype: object

In [40]:
master_df["delivery_days"] = (
    master_df["order_delivered_customer_date"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

master_df["estimated_delivery_days"] = (
    master_df["order_estimated_delivery_date"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

master_df["delivery_delay_days"] = (
    master_df["order_delivered_customer_date"]
    - master_df["order_estimated_delivery_date"]
).dt.total_seconds() / (24 * 60 * 60)

print(
    master_df[
        [
            "delivery_days",
            "estimated_delivery_days",
            "delivery_delay_days"
        ]
    ].head()
)

   delivery_days  estimated_delivery_days  delivery_delay_days
0       8.436574                15.544063            -7.107488
1      13.782037                19.137766            -5.355729
2       9.394213                26.639711           -17.245498
3      13.208750                26.188819           -12.980069
4       2.873877                12.112049            -9.238171

In [41]:
master_df["approval_delay_hours"] = (
    master_df["order_approved_at"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / 3600

master_df["shipping_delay_days"] = (
    master_df["shipping_limit_date"]
    - master_df["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

print(
    master_df[
        [
            "approval_delay_hours",
            "shipping_delay_days"
        ]
    ].head()
)

   approval_delay_hours  shipping_delay_days
0              0.178333             4.007431
1             30.713889             5.279745
2              0.276111             5.011505
3              0.298056             5.012419
4              1.030556             5.967338

In [42]:
master_df["is_delayed"] = (
    master_df["delivery_delay_days"] > 0
).astype(int)

print(master_df["is_delayed"].value_counts())

is_delayed
0    1646121
1     252109
Name: count, dtype: int64

In [43]:
master_df["total_order_value"] = (
    master_df["price"] +
    master_df["freight_value"]
)

print(
    master_df[
        ["price", "freight_value", "total_order_value"]
    ].head()
)

    price  freight_value  total_order_value
0   29.99           8.72              38.71
1  118.70          22.76             141.46
2  159.90          19.22             179.12
3   45.00          27.20              72.20
4   19.90           8.72              28.62

In [44]:
master_df["freight_percentage"] = (
    master_df["freight_value"] /
    master_df["price"].replace(0, pd.NA)
) * 100

print(master_df["freight_percentage"].describe())

count    1.898230e+06
mean     9.820599e+01
std      1.900273e+02
min      0.000000e+00
25%      1.437037e+01
50%      2.476714e+01
75%      5.571429e+01
max      2.623529e+03
Name: freight_percentage, dtype: float64

In [45]:
master_df["price_log"] = np.log1p(master_df["price"])

master_df["freight_log"] = np.log1p(master_df["freight_value"])

print(
    master_df[
        ["price", "price_log", "freight_value", "freight_log"]
    ].head()
)

    price  price_log  freight_value  freight_log
0   29.99   3.433665           8.72     2.274186
1  118.70   4.784989          22.76     3.168003
2  159.90   5.080783          19.22     3.006672
3   45.00   3.828641          27.20     3.339322
4   19.90   3.039749           8.72     2.274186

In [46]:
# ============================================================
# CUSTOMER HISTORICAL FEATURES
# ============================================================

customer_features = (
    master_df[
        [
            "order_id",
            "customer_unique_id",
            "order_purchase_timestamp",
            "total_order_value",
            "price"
        ]
    ]
    .drop_duplicates("order_id")
    .copy()
)

customer_features = customer_features.sort_values(
    [
        "customer_unique_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

# Number of previous orders
customer_features["customer_order_count"] = (
    customer_features
    .groupby("customer_unique_id")
    .cumcount()
)

# Previous total spending
customer_features["customer_total_spend"] = (
    customer_features
    .groupby("customer_unique_id")["total_order_value"]
    .transform(
        lambda x: x.shift(1).fillna(0).cumsum()
    )
)

# Previous average order value
customer_features["customer_avg_order_value"] = (
    customer_features["customer_total_spend"]
    /
    customer_features["customer_order_count"].replace(
        0, np.nan
    )
).fillna(0)

# Previous average price
customer_features["customer_avg_price"] = (
    customer_features
    .groupby("customer_unique_id")["price"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
).fillna(0)

master_df = master_df.drop(
    columns=[
        "customer_order_count",
        "customer_total_spend",
        "customer_avg_order_value",
        "customer_avg_price"
    ],
    errors="ignore"
)

master_df = master_df.merge(
    customer_features[
        [
            "order_id",
            "customer_order_count",
            "customer_total_spend",
            "customer_avg_order_value",
            "customer_avg_price"
        ]
    ],
    on="order_id",
    how="left"
)

print(
    master_df[
        [
            "customer_order_count",
            "customer_total_spend",
            "customer_avg_order_value",
            "customer_avg_price"
        ]
    ].head()
)

   customer_order_count  customer_total_spend  customer_avg_order_value  \
0                     1                 44.11                     44.11
1                     0                  0.00                      0.00
2                     0                  0.00                      0.00
3                     0                  0.00                      0.00
4                     0                  0.00                      0.00

   customer_avg_price
0               35.39
1                0.00
2                0.00
3                0.00
4                0.00

In [47]:
# ============================================================
# PRODUCT HISTORICAL FEATURES
# ============================================================

product_features = (
    master_df[
        [
            "order_id",
            "product_id",
            "order_purchase_timestamp",
            "total_order_value",
            "price",
            "freight_value"
        ]
    ]
    .copy()
)

product_features = product_features.sort_values(
    [
        "product_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

# Previous product order count
product_features["product_order_count"] = (
    product_features
    .groupby("product_id")
    .cumcount()
)

# Previous product revenue
product_features["product_total_revenue"] = (
    product_features
    .groupby("product_id")["total_order_value"]
    .transform(
        lambda x: x.shift(1).fillna(0).cumsum()
    )
)

# Previous average price
product_features["product_avg_price"] = (
    product_features
    .groupby("product_id")["price"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
).fillna(0)

# Previous average freight
product_features["product_avg_freight"] = (
    product_features
    .groupby("product_id")["freight_value"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
).fillna(0)

master_df = master_df.drop(
    columns=[
        "product_order_count",
        "product_total_revenue",
        "product_avg_price",
        "product_avg_freight"
    ],
    errors="ignore"
)

product_feature_cols = [
    "product_order_count",
    "product_total_revenue",
    "product_avg_price",
    "product_avg_freight"
]

master_df[product_feature_cols] = (
    product_features
    .set_index(product_features.index)[product_feature_cols]
    .reindex(master_df.index)
    .fillna(0)
)

print(
    master_df[
        [
            "product_order_count",
            "product_total_revenue",
            "product_avg_price",
            "product_avg_freight"
        ]
    ].head()
)

   product_order_count  product_total_revenue  product_avg_price  \
0                    2                  75.54              29.99
1                  157               20832.80             119.10
2                    2                 356.00             158.90
3                    8                 454.32              45.00
4                   36                1207.92              19.90

   product_avg_freight
0             7.780000
1            13.592994
2            19.100000
3            11.790000
4            13.653333

In [48]:
# ============================================================
# SELLER HISTORICAL FEATURES
# ============================================================

seller_features = (
    master_df[
        [
            "order_id",
            "seller_id",
            "order_purchase_timestamp",
            "total_order_value",
            "price",
            "freight_value"
        ]
    ]
    .copy()
)

seller_features = seller_features.sort_values(
    [
        "seller_id",
        "order_purchase_timestamp",
        "order_id"
    ]
)

seller_features["seller_order_count"] = (
    seller_features
    .groupby("seller_id")
    .cumcount()
)

seller_features["seller_total_revenue"] = (
    seller_features
    .groupby("seller_id")["total_order_value"]
    .transform(
        lambda x: x.shift(1).fillna(0).cumsum()
    )
)

seller_features["seller_avg_price"] = (
    seller_features
    .groupby("seller_id")["price"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
).fillna(0)

seller_features["seller_avg_freight"] = (
    seller_features
    .groupby("seller_id")["freight_value"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
).fillna(0)

master_df = master_df.drop(
    columns=[
        "seller_order_count",
        "seller_total_revenue",
        "seller_avg_price",
        "seller_avg_freight"
    ],
    errors="ignore"
)

# Add historical seller features back to master_df
seller_feature_cols = [
    "seller_order_count",
    "seller_total_revenue",
    "seller_avg_price",
    "seller_avg_freight"
]

master_df[seller_feature_cols] = (
    seller_features[seller_feature_cols]
    .reindex(master_df.index)
    .fillna(0)
)

print(
    master_df[
        [
            "seller_order_count",
            "seller_total_revenue",
            "seller_avg_price",
            "seller_avg_freight"
        ]
    ].head()
)

   seller_order_count  seller_total_revenue  seller_avg_price  \
0                  48               3169.39         45.343125
1                 650              44460.84         52.372646
2                2099             424044.07        186.293244
3                  74               7621.12         82.902703
4                 402              10658.08         13.991443

   seller_avg_freight
0           20.685833
1           16.028646
2           15.728704
3           20.085405
4           12.521194

In [49]:
# ============================================================
# STATE HISTORICAL FEATURES
# ============================================================

state_features = (
    master_df[
        [
            "order_id",
            "customer_state",
            "order_purchase_timestamp",
            "total_order_value"
        ]
    ]
    .drop_duplicates("order_id")
    .copy()
)

state_features = state_features.sort_values(
    [
        "customer_state",
        "order_purchase_timestamp",
        "order_id"
    ]
)

state_features["state_order_count"] = (
    state_features
    .groupby("customer_state")
    .cumcount()
)

state_features["state_total_revenue"] = (
    state_features
    .groupby("customer_state")["total_order_value"]
    .transform(
        lambda x: x.shift(1).fillna(0).cumsum()
    )
)

state_features["state_avg_order_value"] = (
    state_features["state_total_revenue"]
    /
    state_features["state_order_count"].replace(
        0, np.nan
    )
).fillna(0)

master_df = master_df.drop(
    columns=[
        "state_order_count",
        "state_total_revenue",
        "state_avg_order_value"
    ],
    errors="ignore"
)

master_df = master_df.merge(
    state_features[
        [
            "order_id",
            "state_order_count",
            "state_total_revenue",
            "state_avg_order_value"
        ]
    ],
    on="order_id",
    how="left"
)

print(
    master_df[
        [
            "state_order_count",
            "state_total_revenue",
            "state_avg_order_value"
        ]
    ].head()
)

   state_order_count  state_total_revenue  state_avg_order_value
0              10618           1420839.32             133.814214
1               3120            512128.45             164.143734
2               1928            295794.38             153.420322
3                182             31819.12             174.830330
4              21827           2839632.97             130.097263

In [50]:
# ============================================================
# PREVIOUS MONTH DEMAND FEATURES
# ============================================================

monthly_data = (
    master_df[
        [
            "order_id",
            "order_purchase_timestamp",
            "order_year",
            "order_month",
            "total_order_value",
            "price"
        ]
    ]
    .drop_duplicates("order_id")
    .copy()
)

monthly_summary = (
    monthly_data
    .groupby(
        ["order_year", "order_month"],
        as_index=False
    )
    .agg(
        monthly_orders=("order_id", "nunique"),
        monthly_revenue=("total_order_value", "sum"),
        monthly_avg_price=("price", "mean")
    )
)

monthly_summary = monthly_summary.sort_values(
    ["order_year", "order_month"]
)

# Previous month's information
monthly_summary["previous_month_orders"] = (
    monthly_summary["monthly_orders"]
    .shift(1)
    .fillna(0)
)

monthly_summary["previous_month_revenue"] = (
    monthly_summary["monthly_revenue"]
    .shift(1)
    .fillna(0)
)

monthly_summary["previous_month_avg_price"] = (
    monthly_summary["monthly_avg_price"]
    .shift(1)
    .fillna(0)
)

master_df = master_df.merge(
    monthly_summary[
        [
            "order_year",
            "order_month",
            "previous_month_orders",
            "previous_month_revenue",
            "previous_month_avg_price"
        ]
    ],
    on=["order_year", "order_month"],
    how="left"
)

print(
    master_df[
        [
            "previous_month_orders",
            "previous_month_revenue",
            "previous_month_avg_price"
        ]
    ].head()
)

   previous_month_orders  previous_month_revenue  previous_month_avg_price
0                 4243.0               644716.34                131.935826
1                 6160.0               929936.34                128.263369
2                 6273.0               964119.03                130.484054
3                 4568.0               693990.45                131.868487
4                 7220.0              1006927.93                120.122575

In [51]:
print("Product-related columns:")
print(
    [
        col for col in master_df.columns
        if "product" in col.lower()
    ]
)

Product-related columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_popularity', 'product_order_count', 'product_total_revenue', 'product_avg_price', 'product_avg_freight']

In [52]:
print("Master dataset shape:", master_df.shape)

Master dataset shape: (1898230, 72)

In [53]:
print(
    [
        col for col in master_df.columns
        if col in [
            "product_order_count",
            "product_total_revenue",
            "product_avg_price",
            "product_avg_freight"
        ]
    ]
)

['product_order_count', 'product_total_revenue', 'product_avg_price', 'product_avg_freight']

In [54]:
# ============================================================
# DEMAND LEVEL
# ============================================================

master_df["demand_level"] = pd.qcut(
    master_df["product_order_count"],
    q=3,
    labels=["Low", "Medium", "High"],
    duplicates="drop"
)

print(
    master_df["demand_level"].value_counts()
)

demand_level
Low       632878
High      632732
Medium    632620
Name: count, dtype: int64

In [55]:
print(master_df["demand_level"].value_counts())

demand_level
Low       632878
High      632732
Medium    632620
Name: count, dtype: int64

In [56]:
print(
    master_df[
        [
            "product_id",
            "product_order_count",
            "product_total_revenue",
            "product_avg_price",
            "product_avg_freight",
            "demand_level"
        ]
    ].head(10)
)

                         product_id  product_order_count  \
0  87285b34884572647811a353c7ac498a                    2
1  595fac2a385ac33a80bd5114aec74eb8                  157
2  aa4383b373c6aca5d8797843e5594415                    2
3  d0b61bfb1de832b15ba9d266ca96e5b0                    8
4  65266b2da20d04dbe00c5c2d3bb7859e                   36
5  060cb19345d90064d1015407193c233d                   54
6  a1804276d9941ac0733cfd409f5206eb                    0
7  4520766ec412348b8d4caa5e8a18c464                    8
8  ac1789e492dcd698c5c10b97a671243a                    0
9  9a78fb9862b10749a117f7fc3c31f051                    5

   product_total_revenue  product_avg_price  product_avg_freight demand_level
0                  75.54              29.99             7.780000          Low
1               20832.80             119.10            13.592994          Low
2                 356.00             158.90            19.100000          Low
3                 454.32              45.00            11.790000          Low
4                1207.92              19.90            13.653333          Low
5                9062.60             147.90            19.925926          Low
6                   0.00               0.00             0.000000          Low
7                 582.17              58.74            14.031250          Low
8                   0.00               0.00             0.000000          Low
9                 985.86             163.96            33.212000          Low

In [57]:
print("Total missing values:", master_df.isnull().sum().sum())

Total missing values: 89868

In [58]:
missing_values = master_df.isnull().sum()

print(
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

delivery_days                    23794
order_delivered_customer_date    23794
delivery_delay_days              23794
order_delivered_carrier_date     18428
order_approved_at                   29
approval_delay_hours                29
dtype: int64

In [59]:
print(master_df.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'total_payment_value', 'payment_count', 'max_installments', 'order_year', 'order_month', 'order_day', 'order_day_of_week', 'order_hour', 'order_week', 'is_weekend', 'delivery_days', 'estimated_delivery_days', 'delivery_delay_days', 'is_delayed', 'item_total_value', 'freight_percentage', 'payment_price_difference', 'log_price', 'is_repeat_customer', 'product_popularity', 'category_order_count', 'city_order_count', 'payment_price_ratio', 'approval_delay_hours', 'shipping_delay_days', 'total_order_value', 'price_log', 'freight_log', 'customer_order_count', 'customer_total_spend', 'customer_avg_order_value', 'customer_avg_price', 'product_order_count', 'product_total_revenue', 'product_avg_price', 'product_avg_freight', 'seller_order_count', 'seller_total_revenue', 'seller_avg_price', 'seller_avg_freight', 'state_order_count', 'state_total_revenue', 'state_avg_order_value', 'previous_month_orders', 'previous_month_revenue', 'previous_month_avg_price', 'demand_level']

In [60]:
ml_df = master_df.copy()

In [61]:
id_columns = [
    "order_id",
    "customer_id",
    "customer_unique_id",
    "order_item_id",
    "product_id",
    "seller_id"
]

ml_df = ml_df.drop(
    columns=id_columns,
    errors="ignore"
)

In [62]:
datetime_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date"
]

ml_df = ml_df.drop(
    columns=datetime_columns,
    errors="ignore"
)

In [63]:
# ============================================================
# REMOVE TARGET AND DELIVERY LEAKAGE FROM ML FEATURES
# ============================================================

# Save target separately
y = ml_df["is_delayed"].copy()

leakage_columns = [
    "is_delayed",
    "delivery_days",
    "delivery_delay_days",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

ml_df = ml_df.drop(
    columns=leakage_columns,
    errors="ignore"
)

print("Target shape:", y.shape)

Target shape: (1898230,)

In [64]:
# Fill missing values in numeric columns
numeric_columns = ml_df.select_dtypes(
    include=["int64", "float64"]
).columns

for col in numeric_columns:
    ml_df[col] = ml_df[col].fillna(
        ml_df[col].median()
    )


# Fill missing values in categorical columns
categorical_columns = ml_df.select_dtypes(
    include=["object", "category"]
).columns

for col in categorical_columns:
    ml_df[col] = ml_df[col].astype("object")
    ml_df[col] = ml_df[col].fillna("Unknown")


# Check remaining missing values
print(
    "Total missing values:",
    ml_df.isnull().sum().sum()
)

Total missing values: 0

In [65]:
print("ML dataset shape:", ml_df.shape)
print(ml_df.dtypes.value_counts())

ML dataset shape: (1898230, 58)
float64    38
int64      10
object      5
int32       5
Name: count, dtype: int64

In [66]:
print(
    ml_df[
        [
            "price",
            "product_order_count",
            "product_avg_price",
            "customer_order_count",
            "customer_total_spend",
            "customer_avg_order_value",
            "demand_level"
        ]
    ].head()
)

    price  product_order_count  product_avg_price  customer_order_count  \
0   29.99                    2              29.99                     1
1  118.70                  157             119.10                     0
2  159.90                    2             158.90                     0
3   45.00                    8              45.00                     0
4   19.90                   36              19.90                     0

   customer_total_spend  customer_avg_order_value demand_level
0                 44.11                     44.11          Low
1                  0.00                      0.00          Low
2                  0.00                      0.00          Low
3                  0.00                      0.00          Low
4                  0.00                      0.00          Low

In [67]:
# ============================================================
# SAVE ML DATASET
# ============================================================

FEATURE_PATH = (
    PROJECT_ROOT /
    "data" /
    "processed" /
    "feature_engineered_dataset.csv"
)

ml_df.to_csv(
    FEATURE_PATH,
    index=False
)

print("Saved:", FEATURE_PATH)
print("Shape:", ml_df.shape)

Saved: d:\pricing-optimization-system\data\processed\feature_engineered_dataset.csv
Shape: (1898230, 58)

In [68]:
MASTER_FEATURE_PATH = (
    PROJECT_ROOT /
    "data" /
    "processed" /
    "master_dataset_featured.csv"
)

master_df.to_csv(
    MASTER_FEATURE_PATH,
    index=False
)

print("Saved:", MASTER_FEATURE_PATH)

Saved: d:\pricing-optimization-system\data\processed\master_dataset_featured.csv

In [69]:
print("Final Master Dataset")
print("--------------------")
print("Rows:", master_df.shape[0])
print("Columns:", master_df.shape[1])

print("\nML Dataset")
print("----------")
print("Rows:", ml_df.shape[0])
print("Columns:", ml_df.shape[1])

print("\nTarget")
print("------")
print("Target rows:", y.shape[0])

print("\nMissing values in ML dataset:")
print(ml_df.isnull().sum().sum())

Final Master Dataset
--------------------
Rows: 1898230
Columns: 73

ML Dataset
----------
Rows: 1898230
Columns: 58

Target
------
Target rows: 1898230

Missing values in ML dataset:
0

In [70]:
new_features = [
    "order_year",
    "order_month",
    "order_day",
    "order_day_of_week",
    "order_hour",
    "order_week",
    "is_weekend",

    "delivery_days",
    "estimated_delivery_days",
    "delivery_delay_days",
    "approval_delay_hours",
    "shipping_delay_days",
    "is_delayed",

    "item_total_value",
    "total_order_value",
    "freight_percentage",
    "payment_price_difference",
    "payment_price_ratio",
    "log_price",
    "price_log",
    "freight_log",

    "customer_order_count",
    "is_repeat_customer",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_price",

    "product_order_count",
    "product_popularity",
    "product_total_revenue",
    "product_avg_price",
    "product_avg_freight",

    "seller_order_count",
    "seller_total_revenue",
    "seller_avg_price",
    "seller_avg_freight",

    "category_order_count",

    "state_order_count",
    "state_total_revenue",
    "state_avg_order_value",

    "city_order_count",

    "previous_month_orders",
    "previous_month_revenue",
    "previous_month_avg_price",

    "demand_level"
]

print(
    "Number of engineered features:",
    len(new_features)
)

print("\nEngineered features:")

for feature in new_features:
    if feature in master_df.columns:
        print("-", feature)

Number of engineered features: 44

Engineered features:
- order_year
- order_month
- order_day
- order_day_of_week
- order_hour
- order_week
- is_weekend
- delivery_days
- estimated_delivery_days
- delivery_delay_days
- approval_delay_hours
- shipping_delay_days
- is_delayed
- item_total_value
- total_order_value
- freight_percentage
- payment_price_difference
- payment_price_ratio
- log_price
- price_log
- freight_log
- customer_order_count
- is_repeat_customer
- customer_total_spend
- customer_avg_order_value
- customer_avg_price
- product_order_count
- product_popularity
- product_total_revenue
- product_avg_price
- product_avg_freight
- seller_order_count
- seller_total_revenue
- seller_avg_price
- seller_avg_freight
- category_order_count
- state_order_count
- state_total_revenue
- state_avg_order_value
- city_order_count
- previous_month_orders
- previous_month_revenue
- previous_month_avg_price
- demand_level

In [71]:
master_df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
order_id,1898230,98666,8272b63d03f5f79c56e9e4120aec44ef,194481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,1898230,98666,fc3d1daec319d62d49bfb5e1f83123e9,194481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_status,1898230,7,delivered,1874423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_purchase_timestamp,1898230,NaN,NaN,NaN,2017-12-10 05:06:10.099988992,2016-09-04 21:15:19,2017-08-23 09:22:34,2017-12-13 14:21:15,2018-03-25 10:28:16,2018-09-03 09:06:57,NaN
order_approved_at,1898201,NaN,NaN,NaN,2017-12-11 00:58:52.201762816,2016-09-15 12:16:38,2017-08-24 14:30:23,2017-12-15 02:30:41,2018-03-25 14:30:49,2018-09-03 17:40:06,NaN
...,...,...,...,...,...,...,...,...,...,...,...
state_avg_order_value,1898230.0,NaN,NaN,NaN,143.724192,0.0,130.625515,137.15971,151.192591,1071.64,19.723266
previous_month_orders,1898230.0,NaN,NaN,NaN,5233.389571,0.0,3969.0,5624.0,7188.0,7451.0,1926.846729
previous_month_revenue,1898230.0,NaN,NaN,NaN,756163.583925,0.0,531330.07,801199.79,1006927.93,1056929.42,277525.347789
previous_month_avg_price,1898230.0,NaN,NaN,NaN,120.861919,0.0,120.122575,125.482156,131.469713,146.625292,21.71041
demand_level,1898230,3,Low,632878,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
ml_df.head()

,order_status,customer_zip_code_prefix,customer_city,customer_state,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,...,seller_total_revenue,seller_avg_price,seller_avg_freight,state_order_count,state_total_revenue,state_avg_order_value,previous_month_orders,previous_month_revenue,previous_month_avg_price,demand_level
0,delivered,3149,sao paulo,SP,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,...,3169.39,45.343125,20.685833,10618,1420839.32,133.814214,4243.0,644716.34,131.935826,Low
1,delivered,47813,barreiras,BA,118.70,22.76,perfumaria,29.0,178.0,1.0,...,44460.84,52.372646,16.028646,3120,512128.45,164.143734,6160.0,929936.34,128.263369,Low
2,delivered,75265,vianopolis,GO,159.90,19.22,automotivo,46.0,232.0,1.0,...,424044.07,186.293244,15.728704,1928,295794.38,153.420322,6273.0,964119.03,130.484054,Low
3,delivered,59296,sao goncalo do amarante,RN,45.00,27.20,pet_shop,59.0,468.0,3.0,...,7621.12,82.902703,20.085405,182,31819.12,174.830330,4568.0,693990.45,131.868487,Low
4,delivered,9195,santo andre,SP,19.90,8.72,papelaria,38.0,316.0,4.0,...,10658.08,13.991443,12.521194,21827,2839632.97,130.097263,7220.0,1006927.93,120.122575,Low

In [73]:
ml_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898230 entries, 0 to 1898229
Data columns (total 58 columns):
 #   Column                      Dtype
---  ------                      -----
 0   order_status                object
 1   customer_zip_code_prefix    int64
 2   customer_city               object
 3   customer_state              object
 4   price                       float64
 5   freight_value               float64
 6   product_category_name       object
 7   product_name_lenght         float64
 8   product_description_lenght  float64
 9   product_photos_qty          float64
 10  product_weight_g            float64
 11  product_length_cm           float64
 12  product_height_cm           float64
 13  product_width_cm            float64
 14  total_payment_value         float64
 15  payment_count               float64
 16  max_installments            float64
 17  order_year                  int32
 18  order_month                 int32
 19  order_day                   int32
 20  order_day_of_week           int32
 21  order_hour                  int32
 22  order_week                  int64
 23  is_weekend                  int64
 24  estimated_delivery_days     float64
 25  item_total_value            float64
 26  freight_percentage          float64
 27  payment_price_difference    float64
 28  log_price                   float64
 29  is_repeat_customer          int64
 30  product_popularity          int64
 31  category_order_count        float64
 32  city_order_count            int64
 33  payment_price_ratio         float64
 34  approval_delay_hours        float64
 35  shipping_delay_days         float64
 36  total_order_value           float64
 37  price_log                   float64
 38  freight_log                 float64
 39  customer_order_count        int64
 40  customer_total_spend        float64
 41  customer_avg_order_value    float64
 42  customer_avg_price          float64
 43  product_order_count         int64
 44  product_total_revenue       float64
 45  product_avg_price           float64
 46  product_avg_freight         float64
 47  seller_order_count          int64
 48  seller_total_revenue        float64
 49  seller_avg_price            float64
 50  seller_avg_freight          float64
 51  state_order_count           int64
 52  state_total_revenue         float64
 53  state_avg_order_value       float64
 54  previous_month_orders       float64
 55  previous_month_revenue      float64
 56  previous_month_avg_price    float64
 57  demand_level                object
dtypes: float64(38), int32(5), int64(10), object(5)
memory usage: 803.8+ MB